---
#--------------------------------------------------------------#
# Register Instance DNS Name                       [register_dns]
#--------------------------------------------------------------#
- name: register postgres instance dns
  tags: pg_dns_ins
  delegate_to: '{{ item }}'
  with_items: "{{ groups['infra'] | default([]) }}"
  copy:
    dest: /etc/hosts.d/{{ pg_instance }}
    mode: 0644
    owner: root
    group: root
    content: "{{ inventory_hostname }} {{ pg_instance }}"

# write dns records to infra nodes' /etc/hosts.d/<pg_cluster>
- name: register postgres cluster dns
  tags: pg_dns_cls
  delegate_to: '{{ item }}'
  with_items: "{{ groups['infra'] | default([]) }}"
  ignore_errors: true
  copy:
    dest: /etc/hosts.d/{{ pg_cluster }}
    mode: 0644
    owner: root
    group: root
    content: |
      {% set pg_dns_name = pg_cluster + pg_dns_suffix|default('') %}
      {% if pg_dns_target == 'vip' and pg_vip_enabled|bool %}
      # [VIP] {{ pg_dns_name }} -> {{ pg_vip_address.split('/')[0] }} 
      {{ pg_vip_address.split('/')[0] }} {{ pg_dns_name }}
      {% elif pg_dns_target == 'primary' %}
      # [PRIMARY] {{ pg_dns_name }} -> {{ pg_primary_ip }}
      {{ pg_primary_ip }} {{ pg_dns_name }}
      {% elif pg_dns_target == 'auto' %}
      {% if pg_vip_enabled|bool %}
      # [VIP] {{ pg_dns_name }} -> {{ pg_vip_address.split('/')[0] }} 
      {{ pg_vip_address.split('/')[0] }} {{ pg_dns_name }}
      {% else %}
      # [PRIMARY] {{ pg_dns_name }} -> {{ pg_primary_ip }}
      {{ pg_primary_ip }} {{ pg_dns_name }}
      {% endif %}
      {% elif pg_dns_target|regex_search('^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))?$') %}
      # [ADHOC] {{ pg_dns_name }} -> {{ pg_primary_ip }}
      {{ pg_dns_target }} {{ pg_dns_name }}
      {% endif %}

# reload meta node nginx (maybe not appropriate here)
- name: reload dnsmasq on infra node
  tags: pg_dns_reload
  delegate_to: '{{ item }}'
  run_once: true
  ignore_errors: true
  with_items: '{{ groups["infra"] | default([]) }}'
  systemd: name=dnsmasq state=reloaded enabled=yes daemon_reload=yes
...