# check .env files before running
services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    volumes:
      - /etc/pigsty/pgadmin/servers.json:/pgadmin4/servers.json
      - /etc/pigsty/pgadmin/pgpass:/pgadmin4/pgpass:ro
    ports:
      - "${PGADMIN_PORT}:80"
