# check .env files before running

services:
  postgrest:
    container_name: postgrest
    image: postgrest/postgrest
    restart: always
    environment:
      PGRST_DB_URI        : ${POSTGREST_DB_URI}
      PGRST_DB_SCHEMA     : ${POSTGREST_DB_SCHEMA}
      PGRST_DB_ANON_ROLE  : ${POSTGREST_DB_ANON_ROLE}
      PGRST_SERVER_PORT   : ${POSTGREST_SERVER_PORT}
      PGRST_JWT_SECRET    : ${POSTGREST_JWT_SECRET}
    ports:
      - "${POSTGREST_SERVER_PORT}:${POSTGREST_SERVER_PORT}"