---
#--------------------------------------------------------------#
# Assert etcd identity                             [etcd_assert]
#--------------------------------------------------------------#
- name: assert etcd identity
  tags: etcd_assert
  assert:
    that:
      - etcd_seq is defined and etcd_seq|int >= 0
    fail_msg: variable 'etcd_seq' is required for etcd instance

#--------------------------------------------------------------#
# Install etcd                                    [etcd_install]
#--------------------------------------------------------------#
- name: install etcd
  tags: etcd_install
  package: name=etcd state=present

#--------------------------------------------------------------#
# Create etcd directory                               [etcd_dir]
#--------------------------------------------------------------#
- name: create etcd directories
  tags: etcd_dir
  file: path={{ item.path }} state=directory owner={{ item.owner }} group={{ item.group }} mode={{ item.mode }}
  with_items:
    - { path: "/etc/etcd"       ,mode: "0750" , owner: "etcd" , group: "etcd"  }
    - { path: "/var/lib/etcd"   ,mode: "0750" , owner: "etcd" , group: "etcd"  }
    - { path: "{{ node_data }}" ,mode: "0777" , owner: "root" , group: "root"  }
    - { path: "{{ etcd_data }}" ,mode: "0700" , owner: "etcd" , group: "etcd"  }

#--------------------------------------------------------------#
# Config etcd                                      [etcd_config]
#--------------------------------------------------------------#
- import_tasks: config.yml
  tags: etcd_config
  vars: { etcd_instance: "{{ etcd_cluster }}-{{ etcd_seq }}" }

#--------------------------------------------------------------#
# Add new member                                   [etcd_member]
#--------------------------------------------------------------#
# use etcd member add
- name: add new member to etcd cluster
  tags: etcd_member
  when: etcd_init == 'existing'
  block:

    - name: add new member to etcd cluster
      shell: |
        etcdctl member add "{{ etcd_cluster }}-{{ etcd_seq }}" {% if etcd_learner|bool %}--learner=true{% endif %} --peer-urls=https://{{ inventory_hostname }}:{{ etcd_peer_port }}
      environment:
        ETCDCTL_CACERT: "/etc/etcd/ca.crt"
        ETCDCTL_CERT: "/etc/etcd/server.crt"
        ETCDCTL_KEY: "/etc/etcd/server.key"
        ETCDCTL_ENDPOINTS: "{{ groups[etcd_cluster] | difference([inventory_hostname]) | map('regex_replace', '^(.*)$', '\\1:' + etcd_port|string) | join(',') }}"
      register: etcd_member_add_result
      failed_when:
        - etcd_member_add_result.rc != 0
        - "'Peer URLs already exists' not in etcd_member_add_result.stderr"

    - name: display member add result
      debug:
        msg: >-
          {% if etcd_member_add_result.rc == 0 %}
          Successfully added member {{ etcd_cluster }}-{{ etcd_seq }} to etcd cluster
          {% elif 'Peer URLs already exists' in etcd_member_add_result.stderr %}
          Member {{ etcd_cluster }}-{{ etcd_seq }} already exists in etcd cluster, skipping
          {% else %}
          Unexpected error: {{ etcd_member_add_result.stderr }}
          {% endif %}

#--------------------------------------------------------------#
# Launch etcd                                      [etcd_launch]
#--------------------------------------------------------------#
- name: launch etcd server
  tags: etcd_launch
  block:
    - name: launch etcd server service
      systemd: name=etcd state=restarted enabled=yes daemon_reload=yes
    - name: wait for etcd server online
      wait_for: host=127.0.0.1 port={{ etcd_port }} state=started timeout=10

#--------------------------------------------------------------#
# Register etcd to prometheus                    [etcd_register]
#--------------------------------------------------------------#
- name: register etcd as prometheus target
  tags: [ etcd_register, register_prometheus ]
  when: prometheus_enabled|bool
  ignore_errors: true
  delegate_to: '{{ item }}'
  with_items: '{{ groups["infra"]|default([]) }}'
  copy:
    dest: "{{ prometheus_sd_dir }}/etcd/{{ etcd_cluster }}-{{ etcd_seq }}.yml"
    owner: prometheus
    content: |
      # {{ etcd_cluster }}-{{ etcd_seq }} @ {{ inventory_hostname }}
      - labels: { ip: {{ inventory_hostname }} , ins: {{ etcd_cluster }}-{{ etcd_seq }} , cls: {{ etcd_cluster }} }
        targets: [ {{ inventory_hostname }}:{{ etcd_port }} ]

...