# check .env files before running
services:
  minio:
    container_name: minio
    image: minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: |
      server /data --console-address ":9001"
