---
#--------------------------------------------------------------#
# Remove pgbackrest_exporter                 [pgbackrest_exporter]
#--------------------------------------------------------------#
- name: remove pgbackrest exporter
  tags: pgbackrest_exporter
  become: yes
  ignore_errors: yes
  block:

    - name: stop and disable pgbackrest_exporter service
      systemd: name=pgbackrest_exporter state=stopped enabled=no daemon_reload=yes

    - name: remove pgbackrest_exporter config file
      file: name=/etc/default/pgbackrest_exporter state=absent
...