---
- name: reload pg_exporter
  systemd: name=pg_exporter state=reloaded daemon_reload=yes

- name: restart pg_exporter
  systemd: name=pg_exporter state=restarted daemon_reload=yes

- name: reload pgbouncer_exporter
  systemd: name=pgbouncer_exporter state=reloaded daemon_reload=yes

- name: restart pgbouncer_exporter
  systemd: name=pgbouncer_exporter state=restarted daemon_reload=yes

- name: reload pgbackrest_exporter
  systemd: name=pgbackrest_exporter state=reloaded daemon_reload=yes

- name: restart pgbackrest_exporter
  systemd: name=pgbackrest_exporter state=restarted daemon_reload=yes
...