---
#--------------------------------------------------------------#
# PG_MIGRATION
#--------------------------------------------------------------#
context_dir: ~/migration           # migration manuals & scripts
#--------------------------------------------------------------#
# source cluster       (the old cluster)
#--------------------------------------------------------------#
#src_cls: pg-meta      # src cluster name         <REQUIRED>
#src_db: meta          # src database name        <REQUIRED>
#src_ip: 10.10.10.10   # src cluster primary ip   <REQUIRED>
#src_list: []          # src cluster replicas ip  [OPTIONAL]
#src_dns: pg-meta      # src cluster dns name     [OPTIONAL]
#src_vip: 10.10.10.2   # src cluster vip address  [OPTIONAL]
#src_pg: ''            # if defined, use this as src dbsu pgurl instead of:
#                          postgres://{{ pg_admin_username }}@{{ src_ip }}/{{ src_db }}
#sub_conn: ''          # if defined, use this as subscription connstr instead of:
#                          host={{ src_ip }} dbname={{ src_db }} user={{ pg_replication_username }}'
#--------------------------------------------------------------#
# destination cluster  (the new cluster)
#--------------------------------------------------------------#
#dst_cls: pg-test      # dst cluster name         <REQUIRED>
#dst_db: test          # dst database name        <REQUIRED>
#dst_ip: 10.10.10.11   # dst cluster primary ip   <REQUIRED>
#dst_dns: pg-meta      # dst cluster dns name     [OPTIONAL]
#dst_vip: 10.10.10.3   # dst cluster vip address  [OPTIONAL]
#dst_user: test        # dst cluster user         [OPTIONAL]
#dst_pg: ''            # if defined, use this as dst dbsu pgurl instead of:
#                         postgres://{{ pg_admin_username }}@{{ dst_ip }}/{{ dst_db }}
#--------------------------------------------------------------#


#-----------------------------------------------------------------
# PGSQL
#-----------------------------------------------------------------
pg_dbsu: postgres
pg_replication_username: replicator
pg_replication_password: DBUser.Replicator
pg_admin_username: dbuser_dba
pg_admin_password: DBUser.DBA
pg_monitor_username: dbuser_monitor
pg_monitor_password: DBUser.Monitor
...