---
#--------------------------------------------------------------#
# Register HAProxy to Nginx                     [register_nginx]
#--------------------------------------------------------------#
# nginx are idempotent on multiple meta nodes
- name: register haproxy instance to nginx
  tags: [ haproxy_register, register_nginx ]
  when: haproxy_enabled|bool
  become: yes
  block:

    - name: create nginx config dir for haproxy
      run_once: true
      delegate_to: '{{ item }}'
      with_items: '{{ groups["infra"]|default([]) }}'
      file: path=/etc/nginx/conf.d/haproxy state=directory owner=root

    # /etc/nginx/conf.d/haproxy/upstream-{{ pg_instance }}.conf
    - name: register haproxy upstream to nginx
      delegate_to: '{{ item }}'
      with_items: '{{ groups["infra"]|default([]) }}'
      copy:
        dest: /etc/nginx/conf.d/haproxy/upstream-{{ nodename }}.conf
        content: |
          upstream {{ nodename }} {
              server {{ inventory_hostname }}:{{ haproxy_exporter_port }} max_fails=0;
          }

    # /etc/nginx/conf.d/haproxy/location-{{ pg_instance }}.conf
    - name: register haproxy url location to nginx
      delegate_to: '{{ item }}'
      with_items: '{{ groups["infra"]|default([]) }}'
      copy:
        dest: /etc/nginx/conf.d/haproxy/location-{{ nodename }}.conf
        content: |
          location ^~/{{ nodename }}/ {
              proxy_pass http://{{ nodename }};
              proxy_connect_timeout 1;
          }

    # reload meta node nginx (maybe not appropriate here)
    - name: reload nginx to finish haproxy register
      delegate_to: '{{ item }}'
      run_once: true
      with_items: '{{ groups["infra"]|default([]) }}'
      systemd: name=nginx state=reloaded enabled=yes daemon_reload=yes


#--------------------------------------------------------------#
# Register Instance DNS Name                           [vip_dns]
#--------------------------------------------------------------#
- name: register node vip dns name
  tags: [ node_vip, vip_dns, vip_dns_config ]
  when: vip_enabled|bool
  delegate_to: '{{ item }}'
  with_items: "{{ groups['infra'] | default([]) }}"
  ignore_errors: true
  copy:
    dest: /etc/hosts.d/{{ dnsname }}
    mode: 0644
    owner: root
    group: root
    content: "{{ vip_address }} {{ dnsname }}"
  vars:
    dnsname: "{{ node_cluster }}{{ vip_dns_suffix|default('') }}"

# reload meta node nginx (maybe not appropriate here)
- name: reload dnsmasq on infra node for node vip
  tags: [ node_vip, vip_dns, vip_dns_reload ]
  when: vip_enabled|bool
  delegate_to: '{{ item }}'
  run_once: true
  ignore_errors: true
  with_items: '{{ groups["infra"]|default([]) }}'
  systemd: name=dnsmasq state=reloaded enabled=yes daemon_reload=yes


#--------------------------------------------------------------#
# Config node_exporter                    [node_exporter_config]
#--------------------------------------------------------------#
- name: config node_exporter
  tags: [ node_exporter, node_exporter_config ]
  block:

    - name: config node_exporter systemd unit
      copy: src=node_exporter.service dest={{ systemd_dir }}/node_exporter.service

    - name: config default node_exporter options
      copy:
        dest: /etc/default/node_exporter
        content: |
          NODE_EXPORTER_OPTS="--web.listen-address=':{{ node_exporter_port }}' --web.telemetry-path='{{ exporter_metrics_path }}' {{ node_exporter_options }}"

#--------------------------------------------------------------#
# Launch node_exporter                    [node_exporter_launch]
#--------------------------------------------------------------#
- name: launch node_exporter
  tags: [ node_exporter, node_exporter_launch ]
  when: node_exporter_enabled|bool
  block:
    - name: launch node_exporter systemd service
      systemd: name=node_exporter state=restarted enabled=yes daemon_reload=yes
    - name: wait for node_exporter service online
      wait_for: host=127.0.0.1 port={{ node_exporter_port }} state=started timeout=10


#--------------------------------------------------------------#
# Config keepalived_exporter               [vip_exporter_config]
#--------------------------------------------------------------#
- name: config keepalived_exporter
  tags: [ node_vip, vip_exporter, vip_exporter_config ]
  when: vip_enabled|bool
  block:

    - name: config keepalived_exporter systemd unit
      copy: src=keepalived_exporter.service dest={{ systemd_dir }}/keepalived_exporter.service

    - name: config default keepalived_exporter options
      copy:
        dest: /etc/default/keepalived_exporter
        content: |
          KEEPALIVED_EXPORTER_OPTS="--web.listen-address=':{{ vip_exporter_port }}' --web.telemetry-path='{{ exporter_metrics_path }}'"


#--------------------------------------------------------------#
# Launch keepalived_exporter               [vip_exporter_launch]
#--------------------------------------------------------------#
- name: launch keepalived_exporter
  tags: [ node_vip, vip_exporter, vip_exporter_launch ]
  when: vip_enabled|bool
  block:
    - name: launch keepalived_exporter systemd service
      systemd: name=keepalived_exporter state=restarted enabled=yes daemon_reload=yes
    - name: wait for keepalived_exporter service online
      wait_for: host=127.0.0.1 port={{ vip_exporter_port }} state=started timeout=10


#--------------------------------------------------------------#
# Register Node             [node_register, register_prometheus]
#--------------------------------------------------------------#
# /etc/prometheus/targets/node/{{ ip }}.yml
- name: register node as prometheus target
  tags: [ node_vip, node_register, register_prometheus ]
  ignore_errors: true
  delegate_to: '{{ item }}'
  with_items: '{{ groups["infra"]|default([]) }}'
  copy:
    dest: "{{ prometheus_sd_dir }}/node/{{ inventory_hostname }}.yml"
    owner: prometheus
    content: |
      # {{ inventory_hostname }}
      # node, haproxy, promtail
      - labels: { ip: {{ inventory_hostname }} , ins: {{ nodename }} , cls: {{ node_cluster|default('nodes') }} }
        targets: {% if not node_exporter_enabled|bool and not haproxy_enabled|bool and not promtail_enabled|bool %}[]{% endif %} 
          {% if node_exporter_enabled|bool %}- {{ inventory_hostname }}:{{ node_exporter_port }}{% endif %}
      
          {% if haproxy_enabled|bool %}- {{ inventory_hostname }}:{{ haproxy_exporter_port }}{% endif %}
      
          {% if promtail_enabled|bool %}- {{ inventory_hostname }}:{{ promtail_port }}{% endif %}
      
      {% if vip_enabled|bool and vip_address is defined and vip_address != '' %}
      # keepalived
      - labels: { ip: {{ inventory_hostname }} , ins: {{ nodename }} , cls: {{ node_cluster|default('nodes') }}, vip: {{ vip_address }} }
        targets: [ {{ inventory_hostname }}:{{ vip_exporter_port }} ]
      {% endif %}


- name: register node as ping target
  tags: [ node_register, register_prometheus ]
  ignore_errors: true
  delegate_to: '{{ item }}'
  with_items: '{{ groups["infra"]|default([]) }}'
  copy:
    dest: "{{ prometheus_sd_dir }}/ping/{{ inventory_hostname }}.yml"
    owner: prometheus
    content: |
      # {{ inventory_hostname }}
      - labels: { ip: {{ inventory_hostname }} , ins: {{ nodename }} , cls: {{ node_cluster|default('nodes') }} }
        targets: [ {{inventory_hostname }} ]

- name: register node vip as ping target
  tags: [ node_vip, node_register, register_prometheus ]
  when: vip_enabled|bool and vip_address is defined and vip_address != ''
  ignore_errors: true
  delegate_to: '{{ item }}'
  with_items: '{{ groups["infra"]|default([]) }}'
  copy:
    dest: "{{ prometheus_sd_dir }}/ping/{{ vip_address }}---{{ inventory_hostname }}.yml"
    owner: prometheus
    content: |
      # {{ vip_address }}@{{ inventory_hostname }}
      - labels: { ip: {{ inventory_hostname }} , ins: {{ nodename }} , cls: {{ node_cluster|default('nodes') }}, vip: {{ vip_address }} , job: node-vip }
        targets: [ {{ vip_address }} ]

#--------------------------------------------------------------#
# Promtail                                            [promtail]
#--------------------------------------------------------------#
- import_tasks: promtail.yml
  when: promtail_enabled|bool

#--------------------------------------------------------------#
# Vector (TBD)                                          [vector]
#--------------------------------------------------------------#
# - import_tasks: vector.yml
...